name: api_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2  # Para chamadas HTTP à API
  provider: ^6.1.2  # Para gerenciamento de estado no MVVM
  intl: ^0.19.0  # Para formatar moedas (USD e BRL)
  connectivity_plus: ^6.0.5  # Para verificar conexão com a internet
  logger: ^2.0.2  # Para log de informações e erros

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
